name: Deploy to EC2

on:
  push:
    branches:
      - main  # Ajusta según tus ramas

jobs:
  deploy:
    runs-on: ubuntu-latest  # Puedes ajustar la imagen según tus necesidades

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies and deploy
      run: |
        ssh -i ${{ secrets.SSH_PRIVATE_KEY_PATH }} ubuntu@13.38.119.133 'cd /var/www/html && git pull origin main'
