on:
    push:
      branches:
        - main
  
  jobs:
    deploy:
      runs-on: ubuntu-22.04
  
      steps:
      - name: Checkout repository
        uses: actions/checkout@v2
  
      - name: Install dependencies and deploy
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem
          ssh -i key.pem ubuntu@ec2-13-38-119-133.eu-west-3.compute.amazonaws.com 'cd /var/www/html && git pull origin main'  
