name: Deploy to EC2

on:
  push:
    branches:
      - main  # Cambia esto según el nombre de tu rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: SSH into EC2 and execute commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          cd /var/www/
          sudo rm -rf html
          sudo mkdir html
          cd html
          sudo git clone https://github.com/DiegusNueva/gestor-inventario-poo.git .
          sudo systemctl restart nginx
